apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-storage
  namespace: llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: microk8s-hostpath
